// ── ANIME DATABASE ──────────────────────────────────────────────
const GAME_ID    = 'anime';
const GAME_LABEL = 'ANIME BATTLE';
const GAME_SUB   = 'เลือกอนิเมะที่คุณชอบมากกว่า';
const ITEM_TYPE  = 'anime';
const ANIME = [
  // TOP TIER
  { title:"Attack on Titan",          jp:"進撃の巨人",               genre:"ACTION · DARK FANTASY"      },
  { title:"Death Note",               jp:"デスノート",               genre:"THRILLER · MYSTERY"         },
  { title:"Fullmetal Alchemist: Brotherhood", jp:"鋼の錬金術師",     genre:"ADVENTURE · FANTASY"        },
  { title:"Demon Slayer",             jp:"鬼滅の刃",                 genre:"ACTION · SUPERNATURAL"      },
  { title:"Jujutsu Kaisen",           jp:"呪術廻戦",                 genre:"ACTION · SUPERNATURAL"      },
  { title:"One Piece",                jp:"ワンピース",               genre:"ADVENTURE · FANTASY"        },
  { title:"Naruto",                   jp:"ナルト",                   genre:"ACTION · ADVENTURE"         },
  { title:"Dragon Ball Z",            jp:"ドラゴンボールZ",          genre:"ACTION · MARTIAL ARTS"      },
  { title:"Sword Art Online",         jp:"ソードアート・オンライン", genre:"ACTION · ISEKAI"            },
  { title:"My Hero Academia",         jp:"僕のヒーローアカデミア",   genre:"ACTION · SUPERHERO"         },
  { title:"Hunter x Hunter",          jp:"ハンター×ハンター",        genre:"ACTION · ADVENTURE"         },
  { title:"Bleach",                   jp:"ブリーチ",                 genre:"ACTION · SUPERNATURAL"      },
  { title:"Steins;Gate",              jp:"シュタインズ・ゲート",     genre:"SCI-FI · THRILLER"          },
  { title:"Code Geass",               jp:"コードギアス",             genre:"MECHA · DRAMA"              },
  { title:"Cowboy Bebop",             jp:"カウボーイビバップ",       genre:"SCI-FI · NOIR"              },
  { title:"Neon Genesis Evangelion",  jp:"新世紀エヴァンゲリオン",   genre:"MECHA · PSYCHOLOGICAL"      },
  { title:"Violet Evergarden",        jp:"ヴァイオレット・エヴァーガーデン", genre:"DRAMA · SLICE OF LIFE" },
  { title:"Your Lie in April",        jp:"四月は君の嘘",             genre:"DRAMA · ROMANCE"            },
  { title:"Re:Zero",                  jp:"Re:ゼロから始める異世界生活", genre:"FANTASY · DRAMA"          },
  { title:"Black Clover",             jp:"ブラッククローバー",       genre:"ACTION · FANTASY"           },
  { title:"Vinland Saga",             jp:"ヴィンランド・サガ",       genre:"ACTION · HISTORICAL"        },
  { title:"Spy x Family",             jp:"SPY×FAMILY",               genre:"COMEDY · ACTION"            },
  { title:"Chainsaw Man",             jp:"チェンソーマン",           genre:"ACTION · DARK FANTASY"      },
  { title:"Mob Psycho 100",           jp:"モブサイコ100",            genre:"ACTION · SUPERNATURAL"      },
  { title:"One Punch Man",            jp:"ワンパンマン",             genre:"ACTION · COMEDY"            },
  { title:"Haikyuu!!",                jp:"ハイキュー!!",             genre:"SPORTS · DRAMA"             },
  { title:"Tokyo Ghoul",              jp:"東京喰種",                 genre:"ACTION · HORROR"            },
  { title:"Overlord",                 jp:"オーバーロード",           genre:"FANTASY · ISEKAI"           },
  { title:"No Game No Life",          jp:"ノーゲーム・ノーライフ",   genre:"FANTASY · COMEDY"           },
  { title:"Kaiju No. 8",              jp:"怪獣8号",                  genre:"ACTION · SUPERNATURAL"      },
  // CLASSIC
  { title:"Dragon Ball",              jp:"ドラゴンボール",           genre:"ACTION · ADVENTURE"         },
  { title:"Sailor Moon",              jp:"美少女戦士セーラームーン", genre:"MAGICAL GIRL · ROMANCE"     },
  { title:"Ghost in the Shell",       jp:"攻殻機動隊",               genre:"SCI-FI · CYBERPUNK"         },
  { title:"Yu Yu Hakusho",            jp:"幽☆遊☆白書",              genre:"ACTION · SUPERNATURAL"      },
  { title:"Inuyasha",                 jp:"犬夜叉",                   genre:"ACTION · ROMANCE"           },
  { title:"Rurouni Kenshin",          jp:"るろうに剣心",             genre:"ACTION · HISTORICAL"        },
  { title:"Trigun",                   jp:"トライガン",               genre:"SCI-FI · WESTERN"           },
  { title:"Berserk",                  jp:"ベルセルク",               genre:"DARK FANTASY · ACTION"      },
  { title:"Samurai Champloo",         jp:"サムライチャンプルー",     genre:"ACTION · HISTORICAL"        },
  { title:"Elfen Lied",               jp:"エルフェンリート",         genre:"DARK FANTASY · DRAMA"       },
  { title:"Eureka Seven",             jp:"交響詩篇エウレカセブン",   genre:"MECHA · ROMANCE"            },
  { title:"Outlaw Star",              jp:"星方武侠アウトロースター", genre:"SCI-FI · ADVENTURE"         },
  { title:"Wolf Rain",                jp:"ウルフズ・レイン",         genre:"SCI-FI · DRAMA"             },
  { title:"Trigun Stampede",          jp:"トライガンスタンピード",   genre:"SCI-FI · ACTION"            },
  // ISEKAI
  { title:"That Time I Got Reincarnated as a Slime", jp:"転生したらスライムだった件", genre:"FANTASY · ISEKAI" },
  { title:"Konosuba",                 jp:"この素晴らしい世界に祝福を！", genre:"FANTASY · COMEDY"       },
  { title:"The Rising of the Shield Hero", jp:"盾の勇者の成り上がり", genre:"FANTASY · ISEKAI"         },
  { title:"Mushoku Tensei",           jp:"無職転生",                 genre:"FANTASY · ISEKAI"           },
  { title:"Log Horizon",              jp:"ログ・ホライズン",         genre:"FANTASY · ISEKAI"           },
  { title:"Tanya the Evil",           jp:"幼女戦記",                 genre:"FANTASY · MILITARY"         },
  { title:"Cautious Hero",            jp:"この勇者が俺TUEEEくせに慎重すぎる", genre:"FANTASY · COMEDY" },
  { title:"Arifureta",                jp:"ありふれた職業で世界最強", genre:"FANTASY · ISEKAI"           },
  { title:"The Misfit of Demon King Academy", jp:"魔王学院の不適合者", genre:"FANTASY · ACTION"        },
  { title:"In Another World With My Smartphone", jp:"異世界はスマートフォンとともに。", genre:"FANTASY · ISEKAI" },
  // ROMANCE & SOL
  { title:"Toradora",                 jp:"とらドラ！",               genre:"ROMANCE · COMEDY"           },
  { title:"Clannad After Story",      jp:"CLANNAD AFTER STORY",      genre:"DRAMA · ROMANCE"            },
  { title:"Anohana",                  jp:"あの日見た花の名前を僕達はまだ知らない。", genre:"DRAMA · SUPERNATURAL" },
  { title:"A Silent Voice",           jp:"聲の形",                   genre:"DRAMA · ROMANCE"            },
  { title:"Fruits Basket",            jp:"フルーツバスケット",       genre:"ROMANCE · DRAMA"            },
  { title:"Kaguya-sama Love is War",  jp:"かぐや様は告らせたい",     genre:"ROMANCE · COMEDY"           },
  { title:"Horimiya",                 jp:"ホリミヤ",                 genre:"ROMANCE · SLICE OF LIFE"    },
  { title:"Oregairu",                 jp:"やはり俺の青春ラブコメはまちがっている。", genre:"ROMANCE · DRAMA" },
  { title:"Nisekoi",                  jp:"ニセコイ",                 genre:"ROMANCE · COMEDY"           },
  { title:"Ouran High School Host Club", jp:"桜蘭高校ホスト部",     genre:"ROMANCE · COMEDY"           },
  { title:"Rent-a-Girlfriend",        jp:"彼女、お借りします",       genre:"ROMANCE · COMEDY"           },
  { title:"Quintessential Quintuplets", jp:"五等分の花嫁",           genre:"ROMANCE · COMEDY"           },
  // SPORTS
  { title:"Kuroko Basketball",        jp:"黒子のバスケ",             genre:"SPORTS · ACTION"            },
  { title:"Slam Dunk",                jp:"スラムダンク",             genre:"SPORTS · DRAMA"             },
  { title:"Captain Tsubasa",          jp:"キャプテン翼",             genre:"SPORTS · ACTION"            },
  { title:"Ace of Diamond",           jp:"ダイヤのA",                genre:"SPORTS · DRAMA"             },
  { title:"Yowamushi Pedal",          jp:"弱虫ペダル",               genre:"SPORTS · DRAMA"             },
  { title:"Blue Lock",                jp:"ブルーロック",             genre:"SPORTS · ACTION"            },
  { title:"Sk8 the Infinity",         jp:"SK∞ エスケーエイト",       genre:"SPORTS · ACTION"            },
  { title:"Free",                     jp:"Free!",                    genre:"SPORTS · SLICE OF LIFE"     },
  // SCI-FI & MECHA
  { title:"Gurren Lagann",            jp:"天元突破グレンラガン",     genre:"MECHA · ACTION"             },
  { title:"Darling in the FranXX",    jp:"ダーリン・イン・ザ・フランキス", genre:"MECHA · ROMANCE"      },
  { title:"86 Eighty Six",            jp:"86―エイティシックス―",    genre:"MECHA · MILITARY"           },
  { title:"Psycho-Pass",              jp:"サイコパス",               genre:"SCI-FI · THRILLER"          },
  { title:"Parasyte",                 jp:"寄生獣",                   genre:"SCI-FI · HORROR"            },
  { title:"Aldnoah Zero",             jp:"アルドノア・ゼロ",         genre:"MECHA · SCI-FI"             },
  { title:"Dr Stone",                 jp:"Dr.STONE",                 genre:"SCI-FI · ADVENTURE"         },
  { title:"Cyberpunk Edgerunners",    jp:"サイバーパンク エッジランナーズ", genre:"SCI-FI · ACTION"     },
  // HORROR & DARK
  { title:"Made in Abyss",            jp:"メイドインアビス",         genre:"ADVENTURE · DARK FANTASY"   },
  { title:"The Promised Neverland",   jp:"約束のネバーランド",       genre:"THRILLER · DARK FANTASY"    },
  { title:"Higurashi",                jp:"ひぐらしのなく頃に",       genre:"HORROR · MYSTERY"           },
  { title:"Another",                  jp:"アナザー",                 genre:"HORROR · MYSTERY"           },
  { title:"Hellsing Ultimate",        jp:"HELLSING ULTIMATE",        genre:"ACTION · HORROR"            },
  { title:"Shiki",                    jp:"屍鬼",                     genre:"HORROR · SUPERNATURAL"      },
  { title:"Dorohedoro",               jp:"ドロヘドロ",               genre:"DARK FANTASY · ACTION"      },
  // COMEDY
  { title:"Gintama",                  jp:"銀魂",                     genre:"COMEDY · ACTION"            },
  { title:"Nichijou",                 jp:"日常",                     genre:"COMEDY · SLICE OF LIFE"     },
  { title:"Saiki K",                  jp:"斉木楠雄のΨ難",            genre:"COMEDY · SUPERNATURAL"      },
  { title:"Gekkan Shoujo Nozaki-kun", jp:"月刊少女野崎くん",         genre:"COMEDY · ROMANCE"           },
  { title:"Daily Lives of High School Boys", jp:"男子高校生の日常", genre:"COMEDY · SLICE OF LIFE"     },
  { title:"Grand Blue",               jp:"グランブルーファンタジー", genre:"COMEDY · SLICE OF LIFE"     },
  // RECENT HITS
  { title:"Frieren Beyond Journey End", jp:"葬送のフリーレン",       genre:"FANTASY · DRAMA"            },
  { title:"Oshi no Ko",               jp:"推しの子",                 genre:"DRAMA · MYSTERY"            },
  { title:"Dungeon Meshi",            jp:"ダンジョン飯",             genre:"FANTASY · COMEDY"           },
  { title:"Solo Leveling",            jp:"俺だけレベルアップな件",   genre:"ACTION · FANTASY"           },
  { title:"Dandadan",                 jp:"ダンダダン",               genre:"ACTION · SUPERNATURAL"      },
  { title:"Bocchi the Rock",          jp:"ぼっち・ざ・ろっく！",     genre:"COMEDY · MUSIC"             },
  { title:"Lycoris Recoil",           jp:"リコリス・リコイル",       genre:"ACTION · SLICE OF LIFE"     },
  { title:"Ranking of Kings",         jp:"王様ランキング",           genre:"FANTASY · DRAMA"            },
  // ADVENTURE & SHOUNEN
  { title:"Fairy Tail",               jp:"フェアリーテイル",         genre:"ACTION · FANTASY"           },
  { title:"Black Butler",             jp:"黒執事",                   genre:"MYSTERY · SUPERNATURAL"     },
  { title:"Soul Eater",               jp:"ソウルイーター",           genre:"ACTION · FANTASY"           },
  { title:"Magi",                     jp:"マギ",                     genre:"ADVENTURE · FANTASY"        },
  { title:"The Seven Deadly Sins",    jp:"七つの大罪",               genre:"ACTION · FANTASY"           },
  { title:"Noragami",                 jp:"ノラガミ",                 genre:"ACTION · SUPERNATURAL"      },
  { title:"Fire Force",               jp:"炎炎ノ消防隊",             genre:"ACTION · SUPERNATURAL"      },
  { title:"D Gray-man",               jp:"D.Gray-man",               genre:"ACTION · SUPERNATURAL"      },
  { title:"Black Bullet",             jp:"ブラック・ブレット",       genre:"ACTION · SCI-FI"            },
  { title:"Akame ga Kill",            jp:"アカメが斬る！",           genre:"ACTION · DARK FANTASY"      },
  { title:"Sword Art Online Alicization", jp:"ソードアート・オンライン アリシゼーション", genre:"ACTION · ISEKAI"   },
  { title:"Mirai Nikki",              jp:"未来日記",                 genre:"THRILLER · ROMANCE"         },
  { title:"Akira",                    jp:"AKIRA",                    genre:"SCI-FI · CYBERPUNK"         },
  { title:"Sword Art Online Progressive", jp:"ソードアート・オンライン プログレッシブ", genre:"ACTION · ISEKAI" },
  { title:"Naruto Shippuden",         jp:"ナルト 疾風伝",            genre:"ACTION · ADVENTURE"         },
  { title:"Bleach Thousand-Year Blood War", jp:"ブリーチ 千年血戦篇", genre:"ACTION · SUPERNATURAL"    },
  { title:"Black Clover Movie",       jp:"ブラッククローバー 魔法帝の剣", genre:"ACTION · FANTASY"       },
];
