// ── GAME DATABASE ────────────────────────────────────────────────
const GAME_ID    = 'game';
const GAME_LABEL = 'GAME BATTLE';
const GAME_SUB   = 'เลือกเกมที่คุณชอบมากกว่า';
const ITEM_TYPE  = 'game';
const ANIME = [
  // ── ACTION / ADVENTURE ──────────────────────────────────────────
  { title:"The Legend of Zelda: Breath of the Wild", jp:"ゼルダの伝説 ブレス オブ ザ ワイルド", genre:"ACTION · ADVENTURE" },
  { title:"God of War",                jp:"ゴッド・オブ・ウォー",           genre:"ACTION · ADVENTURE"   },
  { title:"Red Dead Redemption 2",     jp:"レッド・デッド・リデンプション2", genre:"ACTION · OPEN WORLD"  },
  { title:"Grand Theft Auto V",        jp:"グランド・セフト・オートV",       genre:"ACTION · OPEN WORLD"  },
  { title:"The Witcher 3",             jp:"ウィッチャー3",                   genre:"RPG · OPEN WORLD"     },
  { title:"Elden Ring",                jp:"エルデンリング",                  genre:"ACTION · RPG"         },
  { title:"Dark Souls III",            jp:"ダークソウルIII",                 genre:"ACTION · RPG"         },
  { title:"Sekiro",                    jp:"隻狼",                            genre:"ACTION · STEALTH"     },
  { title:"Bloodborne",                jp:"ブラッドボーン",                  genre:"ACTION · RPG"         },
  { title:"Devil May Cry 5",           jp:"デビル メイ クライ 5",           genre:"ACTION · HACK & SLASH" },
  { title:"Bayonetta",                 jp:"ベヨネッタ",                      genre:"ACTION · HACK & SLASH" },
  { title:"Metal Gear Solid V",        jp:"メタルギアソリッドV",             genre:"ACTION · STEALTH"     },
  { title:"Ghost of Tsushima",         jp:"ゴースト オブ ツシマ",           genre:"ACTION · OPEN WORLD"  },
  { title:"Horizon Zero Dawn",         jp:"ホライゾン ゼロ ドーン",         genre:"ACTION · RPG"         },
  { title:"Spider-Man",                jp:"マーベルスパイダーマン",          genre:"ACTION · OPEN WORLD"  },
  // ── RPG ──────────────────────────────────────────────────────────
  { title:"Final Fantasy VII",         jp:"ファイナルファンタジーVII",       genre:"JRPG · CLASSIC"       },
  { title:"Final Fantasy VII Remake",  jp:"ファイナルファンタジーVII リメイク", genre:"JRPG · ACTION"      },
  { title:"Final Fantasy XVI",         jp:"ファイナルファンタジーXVI",       genre:"JRPG · ACTION"        },
  { title:"Persona 5 Royal",           jp:"ペルソナ5 ロイヤル",             genre:"JRPG · SOCIAL SIM"    },
  { title:"Persona 4 Golden",          jp:"ペルソナ4 ゴールデン",           genre:"JRPG · SOCIAL SIM"    },
  { title:"Dragon Quest XI",           jp:"ドラゴンクエストXI",              genre:"JRPG · TURN-BASED"    },
  { title:"NieR: Automata",            jp:"ニーア オートマタ",               genre:"ACTION · RPG"         },
  { title:"Tales of Arise",            jp:"テイルズ オブ アライズ",         genre:"JRPG · ACTION"        },
  { title:"Xenoblade Chronicles 3",    jp:"ゼノブレイド クロニクルズ3",     genre:"JRPG · OPEN WORLD"    },
  { title:"Baldurs Gate 3",            jp:"バルダーズゲート3",               genre:"RPG · STRATEGY"       },
  { title:"Divinity Original Sin 2",   jp:"ディヴィニティ:オリジナル シン2", genre:"RPG · STRATEGY"      },
  { title:"Pathfinder Wrath of the Righteous", jp:"パスファインダー",       genre:"RPG · STRATEGY"       },
  // ── SHOOTER ──────────────────────────────────────────────────────
  { title:"Halo Infinite",             jp:"ヘイロー インフィニット",         genre:"FPS · SHOOTER"        },
  { title:"Call of Duty Modern Warfare", jp:"コール オブ デューティ MW",    genre:"FPS · SHOOTER"        },
  { title:"Doom Eternal",              jp:"ドゥーム エターナル",             genre:"FPS · ACTION"         },
  { title:"Titanfall 2",               jp:"タイタンフォール2",               genre:"FPS · ACTION"         },
  { title:"Destiny 2",                 jp:"デスティニー2",                   genre:"FPS · MMO"            },
  { title:"Apex Legends",              jp:"エーペックスレジェンズ",          genre:"FPS · BATTLE ROYALE"  },
  { title:"Valorant",                  jp:"ヴァロラント",                    genre:"FPS · TACTICAL"       },
  { title:"Counter-Strike 2",          jp:"カウンターストライク2",           genre:"FPS · TACTICAL"       },
  { title:"Overwatch 2",               jp:"オーバーウォッチ2",               genre:"FPS · HERO SHOOTER"   },
  { title:"Splatoon 3",                jp:"スプラトゥーン3",                 genre:"TPS · SHOOTER"        },
  // ── PLATFORMER ───────────────────────────────────────────────────
  { title:"Super Mario Odyssey",       jp:"スーパーマリオ オデッセイ",       genre:"PLATFORMER · 3D"      },
  { title:"Super Mario Bros Wonder",   jp:"スーパーマリオブラザーズ ワンダー", genre:"PLATFORMER · 2D"    },
  { title:"Donkey Kong Country Returns", jp:"ドンキーコングリターンズ",     genre:"PLATFORMER · 2D"      },
  { title:"Hollow Knight",             jp:"ホロウナイト",                    genre:"METROIDVANIA · ACTION" },
  { title:"Celeste",                   jp:"セレステ",                        genre:"PLATFORMER · INDIE"   },
  { title:"Ori and the Will of the Wisps", jp:"オリ と蛍火の旅",           genre:"PLATFORMER · INDIE"   },
  { title:"Shovel Knight",             jp:"ショベルナイト",                  genre:"PLATFORMER · INDIE"   },
  { title:"Cuphead",                   jp:"カップヘッド",                    genre:"PLATFORMER · SHOOTER" },
  // ── FIGHTING ─────────────────────────────────────────────────────
  { title:"Street Fighter 6",          jp:"ストリートファイター6",            genre:"FIGHTING · 2D"        },
  { title:"Tekken 8",                  jp:"鉄拳8",                           genre:"FIGHTING · 3D"        },
  { title:"Mortal Kombat 1",           jp:"モータルコンバット1",             genre:"FIGHTING · 2D"        },
  { title:"Super Smash Bros Ultimate", jp:"大乱闘スマッシュブラザーズ SPECIAL", genre:"FIGHTING · PARTY"  },
  { title:"Dragon Ball FighterZ",      jp:"ドラゴンボール ファイターズ",     genre:"FIGHTING · 2D"        },
  { title:"Guilty Gear Strive",        jp:"ギルティギア ストライヴ",         genre:"FIGHTING · 2D"        },
  // ── SPORTS / RACING ──────────────────────────────────────────────
  { title:"FIFA 23",                   jp:"FIFA 23",                         genre:"SPORTS · FOOTBALL"    },
  { title:"eFootball 2024",            jp:"eフットボール 2024",              genre:"SPORTS · FOOTBALL"    },
  { title:"NBA 2K24",                  jp:"NBAツーケー24",                   genre:"SPORTS · BASKETBALL"  },
  { title:"Mario Kart 8 Deluxe",       jp:"マリオカート8 デラックス",        genre:"RACING · KART"        },
  { title:"Gran Turismo 7",            jp:"グランツーリスモ7",               genre:"RACING · SIMULATION"  },
  { title:"Forza Horizon 5",           jp:"フォルツァ ホライゾン5",          genre:"RACING · OPEN WORLD"  },
  { title:"F1 23",                     jp:"F1 23",                           genre:"RACING · SIMULATION"  },
  // ── STRATEGY / PUZZLE ────────────────────────────────────────────
  { title:"Civilization VI",           jp:"シヴィライゼーションVI",           genre:"STRATEGY · TURN-BASED" },
  { title:"StarCraft II",              jp:"スタークラフトII",                 genre:"STRATEGY · RTS"       },
  { title:"Age of Empires IV",         jp:"エイジ オブ エンパイアIV",        genre:"STRATEGY · RTS"       },
  { title:"Total War: Three Kingdoms", jp:"トータルウォー:三国志",           genre:"STRATEGY · GRAND"     },
  { title:"Into the Breach",           jp:"イントゥ・ザ・ブリーチ",          genre:"STRATEGY · PUZZLE"    },
  { title:"Hades",                     jp:"ハデス",                          genre:"ROGUELIKE · ACTION"   },
  { title:"Dead Cells",                jp:"デッドセルズ",                    genre:"ROGUELIKE · ACTION"   },
  { title:"Slay the Spire",            jp:"スレイ・ザ・スパイア",            genre:"ROGUELIKE · CARD"     },
  // ── SURVIVAL / HORROR ────────────────────────────────────────────
  { title:"Resident Evil Village",     jp:"バイオハザード ヴィレッジ",       genre:"HORROR · ACTION"      },
  { title:"Resident Evil 4 Remake",    jp:"バイオハザード4 リメイク",        genre:"HORROR · ACTION"      },
  { title:"Silent Hill 2",             jp:"サイレントヒル2",                 genre:"HORROR · PSYCHOLOGICAL" },
  { title:"Outlast",                   jp:"アウトラスト",                    genre:"HORROR · STEALTH"     },
  { title:"Little Nightmares II",      jp:"リトルナイトメア2",               genre:"HORROR · PUZZLE"      },
  { title:"Subnautica",                jp:"サブノーティカ",                  genre:"SURVIVAL · EXPLORATION" },
  { title:"The Forest",                jp:"ザ フォレスト",                   genre:"SURVIVAL · HORROR"    },
  { title:"Minecraft",                 jp:"マインクラフト",                  genre:"SURVIVAL · SANDBOX"   },
  // ── INDIE ────────────────────────────────────────────────────────
  { title:"Stardew Valley",            jp:"スターデュー バレー",             genre:"SIMULATION · INDIE"   },
  { title:"Undertale",                 jp:"アンダーテール",                  genre:"RPG · INDIE"          },
  { title:"Disco Elysium",             jp:"ディスコ エリジウム",             genre:"RPG · NARRATIVE"      },
  { title:"Outer Wilds",               jp:"アウターワイルズ",                genre:"EXPLORATION · MYSTERY" },
  { title:"Return of the Obra Dinn",   jp:"オブラ・ディン号の帰還",         genre:"MYSTERY · PUZZLE"     },
  { title:"Tunic",                     jp:"チューニック",                    genre:"ACTION · ADVENTURE"   },
  { title:"A Short Hike",              jp:"ア ショート ハイク",              genre:"EXPLORATION · INDIE"  },
  { title:"Unpacking",                 jp:"アンパッキング",                  genre:"PUZZLE · INDIE"       },
  // ── MULTIPLAYER / ONLINE ─────────────────────────────────────────
  { title:"League of Legends",         jp:"リーグ・オブ・レジェンズ",        genre:"MOBA · STRATEGY"      },
  { title:"Dota 2",                    jp:"ドータ2",                         genre:"MOBA · STRATEGY"      },
  { title:"World of Warcraft",         jp:"ワールド・オブ・ウォークラフト",  genre:"MMORPG · ONLINE"      },
  { title:"Final Fantasy XIV",         jp:"ファイナルファンタジーXIV",       genre:"MMORPG · ONLINE"      },
  { title:"Genshin Impact",            jp:"原神",                            genre:"ACTION · RPG"         },
  { title:"Monster Hunter World",      jp:"モンスターハンター: ワールド",    genre:"ACTION · CO-OP"       },
  { title:"Monster Hunter Rise",       jp:"モンスターハンターライズ",        genre:"ACTION · CO-OP"       },
  { title:"Deep Rock Galactic",        jp:"ディープ・ロック・ギャラクティック", genre:"FPS · CO-OP"        },
  // ── RECENT HITS ──────────────────────────────────────────────────
  { title:"Baldurs Gate 3",            jp:"バルダーズゲート3",               genre:"RPG · STRATEGY"       },
  { title:"Alan Wake 2",               jp:"アラン ウェイク2",                genre:"ACTION · HORROR"      },
  { title:"Lies of P",                 jp:"ライズ オブ P",                   genre:"ACTION · SOULSLIKE"   },
  { title:"Armored Core VI",           jp:"アーマード・コア VI",             genre:"ACTION · MECH"        },
  { title:"Starfield",                 jp:"スターフィールド",                genre:"RPG · OPEN WORLD"     },
  { title:"Hogwarts Legacy",           jp:"ホグワーツ レガシー",             genre:"RPG · OPEN WORLD"     },
  { title:"Hi-Fi Rush",                jp:"ハイファイ ラッシュ",             genre:"ACTION · RHYTHM"      },
  { title:"Stray",                     jp:"ストレイ",                        genre:"ADVENTURE · INDIE"    },
  { title:"It Takes Two",              jp:"イット テイクス トゥー",          genre:"PLATFORMER · CO-OP"   },
  { title:"Returnal",                  jp:"リターナル",                      genre:"ROGUELIKE · ACTION"   },
  { title:"Deathloop",                 jp:"デスループ",                      genre:"ACTION · FPS"         },
  { title:"Sifu",                      jp:"師父",                            genre:"ACTION · BRAWLER"     },
  { title:"Nier Replicant",            jp:"ニーア レプリカント",             genre:"ACTION · RPG"         },
  { title:"Cyberpunk 2077",            jp:"サイバーパンク2077",              genre:"RPG · OPEN WORLD"     },
  { title:"Death Stranding",           jp:"デス・ストランディング",          genre:"ACTION · ADVENTURE"   },
  { title:"Control",                   jp:"コントロール",                    genre:"ACTION · SUPERNATURAL" },
];
