// ── SONG DATABASE ────────────────────────────────────────────────
const GAME_ID    = 'song';
const GAME_LABEL = 'SONG BATTLE';
const GAME_SUB   = 'เลือกเพลงที่คุณชอบมากกว่า';
const ITEM_TYPE  = 'song';
const ANIME = [
  // ── POP (THAI) ───────────────────────────────────────────────────
  { title:"เพื่อเธอ",                    jp:"POTATO",                      genre:"POP · THAI"           },
  { title:"รักสามเส้า",                  jp:"Bodyslam",                    genre:"POP · ROCK · THAI"    },
  { title:"ถามหา",                       jp:"Palmy",                       genre:"POP · THAI"           },
  { title:"ค้างคาใจ",                    jp:"Atom ชนกันต์",               genre:"POP · THAI"           },
  { title:"พันธนาการ",                   jp:"Scrubb",                      genre:"POP · INDIE · THAI"   },
  { title:"เพียงชั่วคราว",               jp:"ฟักกลิ้ง ฮีโร่",             genre:"POP · RAP · THAI"     },
  { title:"จดหมายถึงพ่อ",               jp:"PALMY",                       genre:"POP · THAI"           },
  { title:"ดาวที่สวยที่สุด",             jp:"โปเตโต้",                     genre:"POP · THAI"           },
  { title:"เพลงสุดท้าย",                jp:"Peck Palitchoke",             genre:"POP · THAI"           },
  { title:"หนักใจ",                      jp:"Slot Machine",                genre:"POP · ROCK · THAI"    },
  { title:"ทนได้ไง",                     jp:"Bowkylion",                   genre:"POP · INDIE · THAI"   },
  { title:"ไม่ลืม",                      jp:"Jetset'er",                   genre:"POP · THAI"           },
  { title:"อย่าเพิ่งนอน",               jp:"Greasy Cafe",                  genre:"POP · INDIE · THAI"   },
  { title:"นายดีแต่พูด",                jp:"MILLI",                       genre:"RAP · THAI"           },
  { title:"มาตาลดา",                    jp:"Moderndog",                    genre:"ROCK · INDIE · THAI"  },
  // ── ROCK / INDIE ─────────────────────────────────────────────────
  { title:"Bohemian Rhapsody",           jp:"Queen",                        genre:"ROCK · CLASSIC"       },
  { title:"Hotel California",            jp:"Eagles",                       genre:"ROCK · CLASSIC"       },
  { title:"Stairway to Heaven",          jp:"Led Zeppelin",                 genre:"ROCK · CLASSIC"       },
  { title:"Smells Like Teen Spirit",     jp:"Nirvana",                      genre:"ROCK · GRUNGE"        },
  { title:"Wonderwall",                  jp:"Oasis",                        genre:"ROCK · BRITPOP"       },
  { title:"Mr. Brightside",              jp:"The Killers",                  genre:"INDIE · ROCK"         },
  { title:"Seven Nation Army",           jp:"The White Stripes",            genre:"ROCK · INDIE"         },
  { title:"Creep",                       jp:"Radiohead",                    genre:"ROCK · ALTERNATIVE"   },
  { title:"Wish You Were Here",          jp:"Pink Floyd",                   genre:"ROCK · PROGRESSIVE"   },
  { title:"November Rain",               jp:"Guns N Roses",                 genre:"ROCK · CLASSIC"       },
  { title:"Enter Sandman",               jp:"Metallica",                    genre:"HEAVY METAL"          },
  { title:"Basket Case",                 jp:"Green Day",                    genre:"ROCK · PUNK"          },
  { title:"When I Come Around",          jp:"Green Day",                    genre:"ROCK · PUNK"          },
  { title:"Yellow",                      jp:"Coldplay",                     genre:"ROCK · ALTERNATIVE"   },
  { title:"The Scientist",               jp:"Coldplay",                     genre:"POP · ROCK"           },
  // ── POP (GLOBAL) ─────────────────────────────────────────────────
  { title:"Shape of You",                jp:"Ed Sheeran",                   genre:"POP · R&B"            },
  { title:"Bad Guy",                     jp:"Billie Eilish",                genre:"POP · ALTERNATIVE"    },
  { title:"Blinding Lights",             jp:"The Weeknd",                   genre:"POP · SYNTHWAVE"      },
  { title:"Levitating",                  jp:"Dua Lipa",                     genre:"POP · DISCO"          },
  { title:"Drivers License",             jp:"Olivia Rodrigo",               genre:"POP · BALLAD"         },
  { title:"As It Was",                   jp:"Harry Styles",                 genre:"POP · INDIE"          },
  { title:"Anti-Hero",                   jp:"Taylor Swift",                 genre:"POP · SYNTH POP"      },
  { title:"Flowers",                     jp:"Miley Cyrus",                  genre:"POP · DANCE"          },
  { title:"Unholy",                      jp:"Sam Smith",                    genre:"POP · R&B"            },
  { title:"Stay",                        jp:"The Kid LAROI & Justin Bieber", genre:"POP · HIP-HOP"       },
  { title:"Peaches",                     jp:"Justin Bieber",                genre:"POP · R&B"            },
  { title:"Watermelon Sugar",            jp:"Harry Styles",                 genre:"POP · INDIE"          },
  { title:"Heat Waves",                  jp:"Glass Animals",                genre:"POP · INDIE"          },
  { title:"Die For You",                 jp:"The Weeknd",                   genre:"R&B · POP"            },
  { title:"Cruel Summer",                jp:"Taylor Swift",                 genre:"POP · SYNTH POP"      },
  // ── HIP-HOP / R&B ────────────────────────────────────────────────
  { title:"God's Plan",                  jp:"Drake",                        genre:"HIP-HOP · R&B"        },
  { title:"HUMBLE",                      jp:"Kendrick Lamar",               genre:"HIP-HOP · RAP"        },
  { title:"Sicko Mode",                  jp:"Travis Scott",                 genre:"HIP-HOP · TRAP"       },
  { title:"Rockstar",                    jp:"Post Malone",                  genre:"HIP-HOP · POP"        },
  { title:"Sunflower",                   jp:"Post Malone & Swae Lee",       genre:"HIP-HOP · POP"        },
  { title:"Old Town Road",               jp:"Lil Nas X",                    genre:"HIP-HOP · COUNTRY"    },
  { title:"Industry Baby",               jp:"Lil Nas X",                    genre:"HIP-HOP · POP"        },
  { title:"Rich Flex",                   jp:"Drake & 21 Savage",            genre:"HIP-HOP · RAP"        },
  { title:"All Falls Down",              jp:"Kanye West",                   genre:"HIP-HOP · R&B"        },
  { title:"Lose Yourself",               jp:"Eminem",                       genre:"HIP-HOP · RAP"        },
  { title:"Not Like Us",                 jp:"Kendrick Lamar",               genre:"HIP-HOP · RAP"        },
  { title:"N95",                         jp:"Kendrick Lamar",               genre:"HIP-HOP · RAP"        },
  // ── ELECTRONIC / DANCE ───────────────────────────────────────────
  { title:"Titanium",                    jp:"David Guetta ft. Sia",         genre:"ELECTRONIC · POP"     },
  { title:"Wake Me Up",                  jp:"Avicii",                       genre:"ELECTRONIC · FOLK"    },
  { title:"Levels",                      jp:"Avicii",                       genre:"ELECTRONIC · PROGRESSIVE" },
  { title:"Animals",                     jp:"Martin Garrix",                genre:"ELECTRONIC · BIGROOM" },
  { title:"Lean On",                     jp:"Major Lazer & DJ Snake",       genre:"ELECTRONIC · POP"     },
  { title:"One More Time",               jp:"Daft Punk",                    genre:"ELECTRONIC · HOUSE"   },
  { title:"Get Lucky",                   jp:"Daft Punk",                    genre:"ELECTRONIC · FUNK"    },
  { title:"Midnight City",               jp:"M83",                          genre:"ELECTRONIC · INDIE"   },
  { title:"Clarity",                     jp:"Zedd ft. Foxes",               genre:"ELECTRONIC · POP"     },
  { title:"The Less I Know the Better",  jp:"Tame Impala",                  genre:"PSYCHEDELIC · POP"    },
  // ── K-POP ────────────────────────────────────────────────────────
  { title:"Dynamite",                    jp:"BTS",                          genre:"K-POP · DANCE"        },
  { title:"Butter",                      jp:"BTS",                          genre:"K-POP · POP"          },
  { title:"DNA",                         jp:"BTS",                          genre:"K-POP · ELECTROPOP"   },
  { title:"How You Like That",           jp:"BLACKPINK",                    genre:"K-POP · DANCE"        },
  { title:"Pink Venom",                  jp:"BLACKPINK",                    genre:"K-POP · RAP"          },
  { title:"Lovesick Girls",              jp:"BLACKPINK",                    genre:"K-POP · POP"          },
  { title:"Savage",                      jp:"aespa",                        genre:"K-POP · ELECTROPOP"   },
  { title:"Next Level",                  jp:"aespa",                        genre:"K-POP · DANCE"        },
  { title:"FANCY",                       jp:"TWICE",                        genre:"K-POP · POP"          },
  { title:"Cheer Up",                    jp:"TWICE",                        genre:"K-POP · POP"          },
  { title:"My World",                    jp:"aespa",                        genre:"K-POP · ELECTROPOP"   },
  { title:"Hype Boy",                    jp:"NewJeans",                     genre:"K-POP · R&B"          },
  { title:"OMG",                         jp:"NewJeans",                     genre:"K-POP · R&B"          },
  { title:"Super",                       jp:"EXO",                          genre:"K-POP · DANCE"        },
  { title:"Power",                       jp:"EXO",                          genre:"K-POP · DANCE"        },
  // ── J-POP / ANIME OST ────────────────────────────────────────────
  { title:"Gurenge",                     jp:"LiSA",                         genre:"J-POP · ANIME"        },
  { title:"Homura",                      jp:"LiSA",                         genre:"J-POP · ANIME"        },
  { title:"Idol",                        jp:"YOASOBI",                      genre:"J-POP · ANIME"        },
  { title:"Racing into the Night",       jp:"YOASOBI",                      genre:"J-POP · INDIE"        },
  { title:"Pretender",                   jp:"Official HIGE DANdism",        genre:"J-POP"                },
  { title:"Cry Baby",                    jp:"Official HIGE DANdism",        genre:"J-POP · ANIME"        },
  { title:"Blessing",                    jp:"Yuki Hayashi",                 genre:"J-POP · ANIME"        },
  { title:"Renai Circulation",           jp:"Kana Hanazawa",                genre:"J-POP · ANIME"        },
  { title:"Unravel",                     jp:"TK from Ling tosite sigure",   genre:"J-ROCK · ANIME"       },
  { title:"Redo",                        jp:"Konomi Suzuki",                genre:"J-POP · ANIME"        },
  { title:"My Dearest",                  jp:"supercell",                    genre:"J-POP · ANIME"        },
  { title:"Guren no Yumiya",             jp:"Linked Horizon",               genre:"J-ROCK · ANIME"       },
  { title:"Silhouette",                  jp:"KANA-BOON",                    genre:"J-ROCK · ANIME"       },
  { title:"Blue Bird",                   jp:"Ikimono-gakari",               genre:"J-POP · ANIME"        },
  { title:"Again",                       jp:"YUI",                          genre:"J-POP · ANIME"        },
  // ── BALLAD / R&B ─────────────────────────────────────────────────
  { title:"Someone Like You",            jp:"Adele",                        genre:"POP · BALLAD"         },
  { title:"Rolling in the Deep",         jp:"Adele",                        genre:"POP · SOUL"           },
  { title:"Hello",                       jp:"Adele",                        genre:"POP · BALLAD"         },
  { title:"Hallelujah",                  jp:"Jeff Buckley",                 genre:"FOLK · BALLAD"        },
  { title:"Thinking Out Loud",           jp:"Ed Sheeran",                   genre:"POP · R&B"            },
  { title:"Perfect",                     jp:"Ed Sheeran",                   genre:"POP · BALLAD"         },
  { title:"All of Me",                   jp:"John Legend",                  genre:"R&B · BALLAD"         },
  { title:"Let Her Go",                  jp:"Passenger",                    genre:"FOLK · POP"           },
  { title:"Riptide",                     jp:"Vance Joy",                    genre:"INDIE · POP"          },
  { title:"Take Me to Church",           jp:"Hozier",                       genre:"BLUES · SOUL"         },
];
